#ifndef RELAY_H_
#define RELAY_H_

#include "avr_compiler.h"

//Relay timing
#define RELAY_ON_TO       1800  //30min timeout - the maximum duration in the RELAY ON state.
#define RELAY_OFF_TO      30    //30sec timeout - the minimal pause between consecutive RELAY ON states.
#define RELAY_PWR_ON_TO   10    //10seconds. - Delay after power on and relay on condition.

//Relay state mask
#define RELAY_ON          0x0F
#define RELAY_OFF         0x00


typedef struct relay_interface_
{
    uint8_t activity;
    uint16_t operation_timeout; //Relay ON / OFF state's duration. 
    uint8_t state;              //Current state of the relay     
    uint8_t event1;             //Event generated by Temperature sensor 
    uint8_t event2;             //Event generated by Logic Switch
    uint8_t event3;             //Event generated by Voltage control
} relay_t;

void relay_operation(void);

#endif /*RELAY_H_*/